# Generated by Django 3.0.9 on 2021-08-27 08:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WebSite', '0003_videos'),
    ]

    operations = [
        migrations.CreateModel(
            name='customersgroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='ندارد', max_length=500, verbose_name='نام گروه')),
                ('desc', models.CharField(blank=True, default='ندارد', max_length=500, null=True, verbose_name='توضیح گروه')),
                ('Create_Date', models.DateTimeField(auto_now=True)),
                ('Update_Date', models.DateTimeField(auto_now_add=True)),
                ('Create_Uid', models.IntegerField(blank=True, default=0, null=True, verbose_name='کاربر ایجاد کننده')),
                ('Update_Uid', models.IntegerField(blank=True, default=0, null=True, verbose_name='کاربر ویرایش کننده')),
            ],
            options={
                'verbose_name': 'گروه',
                'verbose_name_plural': 'گروه ها',
                'db_table': 'customersgroup',
                'ordering': ['id'],
                'permissions': (('can_read_private_section', 'administrator'), ('SubAdmin', 'SubAdmin'), ('user_watcher', 'User')),
            },
        ),
        migrations.CreateModel(
            name='DiscountCreate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DName', models.CharField(max_length=200, verbose_name='عنوان')),
                ('DiscountType', models.IntegerField(choices=[(0, 'تکی'), (1, 'گروهی')], default=0, verbose_name='نوع تخفیف')),
                ('Ddesc', models.TextField(blank=True, max_length=4000, null=True, verbose_name='شرح')),
                ('Create_Date', models.DateTimeField(auto_now=True)),
                ('Update_Date', models.DateTimeField(auto_now_add=True)),
                ('Create_Uid', models.IntegerField(blank=True, default=0, null=True, verbose_name='کاربر ایجاد کننده')),
                ('Update_Uid', models.IntegerField(blank=True, default=0, null=True, verbose_name='کاربر ویرایش کننده')),
            ],
            options={
                'verbose_name': 'تخفیف',
                'verbose_name_plural': 'تخفیف ها',
                'db_table': 'DiscountCreate',
                'ordering': ['id'],
                'permissions': (('can_read_private_section', 'administrator'), ('SubAdmin', 'SubAdmin'), ('user_watcher', 'User')),
            },
        ),
        migrations.CreateModel(
            name='DiscountFinal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DiscountPriceToSend', models.BigIntegerField(blank=True, default=0, null=True, verbose_name='مبلغ تخفیف ')),
                ('chengetocustosendprice', models.BooleanField(blank=True, default=0, null=True, verbose_name='انتخاب تخفیف روی ارسال')),
                ('DiscounttotalPriceToSend', models.BigIntegerField(blank=True, default=0, null=True, verbose_name='مبلغ تخفیف برای ارسال')),
                ('DmaxPriceToSend', models.BigIntegerField(blank=True, default=0, null=True, verbose_name='سقف تخفیف برای ارسال')),
                ('LimitStartDate', models.DateField(default=datetime.datetime.now, verbose_name='تاریخ شروع محدودیت')),
                ('LimitEndDate', models.DateField(default=datetime.datetime.now, verbose_name='تاریخ پایان محدودیت')),
                ('DiscountCode', models.CharField(default=0, max_length=200, verbose_name='کد تخفیف')),
                ('ShowToCustomers', models.BooleanField(blank=True, default=0, null=True, verbose_name='وضعیت نمایش کد تخفیف')),
                ('changetoproductsgroup', models.BooleanField(blank=True, default=0, null=True, verbose_name='انتخاب گروهی کالا')),
                ('chengetocustomersgroup', models.BooleanField(blank=True, default=0, null=True, verbose_name='انتخاب گروهی مشتری')),
                ('dpricePercent', models.FloatField(blank=True, default=0, null=True, verbose_name='درصد تخفیف ')),
                ('chengepricetoPercent', models.BooleanField(blank=True, default=0, null=True, verbose_name='انتخاب درصدی')),
                ('Create_Date', models.DateTimeField(auto_now=True)),
                ('Update_Date', models.DateTimeField(auto_now_add=True)),
                ('Create_Uid', models.IntegerField(blank=True, default=0, null=True, verbose_name='کاربر ایجاد کننده')),
                ('Update_Uid', models.IntegerField(blank=True, default=0, null=True, verbose_name='کاربر ویرایش کننده')),
                ('DCustomers', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DCustomers', to='WebSite.customersgroup', verbose_name='گروه مشتری ')),
                ('DProducts', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DProducts', to='WebSite.products', verbose_name='کالای انتخاب شده')),
                ('DiscountName', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='DiscountName', to='WebSite.DiscountCreate', verbose_name='نوع تخفیف')),
                ('DiscountToCustomers', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='تخفیف بر روی مشتری')),
                ('DiscountToGoods', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.PROTECT, to='WebSite.productsgroups', verbose_name='تخفیف بر روی گروه کالا')),
            ],
            options={
                'verbose_name': 'کد تخفیف',
                'verbose_name_plural': 'کد های تخفیف',
                'db_table': 'DiscountFinal',
                'ordering': ['id'],
                'permissions': (('can_read_private_section', 'administrator'), ('SubAdmin', 'SubAdmin'), ('user_watcher', 'User')),
            },
        ),
        migrations.CreateModel(
            name='stars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(blank=True, null=True)),
                ('Create_Date', models.DateTimeField(auto_now=True)),
                ('Update_Date', models.DateTimeField(auto_now_add=True)),
                ('uid', models.IntegerField(verbose_name='کاربر')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WebSite.products', verbose_name='کد محصول')),
            ],
            options={
                'verbose_name': 'امتیاز',
                'verbose_name_plural': 'امتیاز ها',
                'db_table': 'stars',
                'ordering': ['id'],
                'permissions': (('can_read_private_section', 'administrator'), ('SubAdmin', 'SubAdmin'), ('user_watcher', 'User')),
            },
        ),
        migrations.CreateModel(
            name='usersendtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sendtype', models.IntegerField(blank=True, choices=[(0, 'تحویل حضوری'), (1, 'ارسال با پیک'), (2, 'ارسال با پست'), (3, 'ارسال با پست پیش تاز')], default=0, null=True, verbose_name='روش ارسال')),
                ('senddate', django_jalali.db.models.jDateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='تاریخ ارسال')),
                ('Create_Date', models.DateTimeField(auto_now=True)),
                ('Update_Date', models.DateTimeField(auto_now_add=True)),
                ('Create_Uid', models.IntegerField(blank=True, default=0, null=True, verbose_name='کاربر ایجاد کننده')),
                ('Update_Uid', models.IntegerField(blank=True, default=0, null=True, verbose_name='کاربر ویرایش کننده')),
            ],
            options={
                'verbose_name': 'وضعیت ارسال',
                'verbose_name_plural': 'وضعیت های ارسال',
                'db_table': 'usersendtype',
                'ordering': ['id'],
                'permissions': (('can_read_private_section', 'administrator'), ('SubAdmin', 'SubAdmin'), ('user_watcher', 'User')),
            },
        ),
        migrations.DeleteModel(
            name='videos',
        ),
        migrations.AddField(
            model_name='finalcheckout',
            name='postcode',
            field=models.CharField(blank=True, default=0, max_length=128, null=True, verbose_name='کد مرسوله'),
        ),
        migrations.AddField(
            model_name='finalcheckout',
            name='senddate',
            field=django_jalali.db.models.jDateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='تاریخ ارسال'),
        ),
        migrations.AddField(
            model_name='finalcheckout',
            name='sendstatus',
            field=models.IntegerField(blank=True, choices=[(0, 'ارسال نشده'), (1, 'ارسال شده'), (2, 'برگشت داده شده')], default=0, null=True, verbose_name='وضعیت ارسال'),
        ),
        migrations.AddField(
            model_name='finalcheckout',
            name='sendtype',
            field=models.IntegerField(blank=True, choices=[(0, 'تحویل حضوری'), (1, 'ارسال با پیک'), (2, 'ارسال با پست'), (3, 'ارسال با پست پیش تاز')], default=0, null=True, verbose_name='روش ارسال'),
        ),
        migrations.AddField(
            model_name='sellbascket',
            name='pgroupid',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='گروه کالا'),
        ),
        migrations.AddField(
            model_name='sellbascket',
            name='price_after_off',
            field=models.BigIntegerField(default=1, verbose_name='مبلغ پس از تخفیف'),
        ),
        migrations.AlterField(
            model_name='firstpagebaners',
            name='group1',
            field=models.ForeignKey(blank=True, default='0', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group1', to='WebSite.productsgroups', verbose_name='گروه بنر 1'),
        ),
        migrations.AlterField(
            model_name='firstpagebaners',
            name='group10',
            field=models.ForeignKey(blank=True, default='0', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group10', to='WebSite.productsgroups', verbose_name='گروه بنر 10'),
        ),
        migrations.AlterField(
            model_name='firstpagebaners',
            name='group11',
            field=models.ForeignKey(blank=True, default='0', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group11', to='WebSite.productsgroups', verbose_name='گروه بنر 11'),
        ),
        migrations.AlterField(
            model_name='firstpagebaners',
            name='group2',
            field=models.ForeignKey(blank=True, default='0', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group2', to='WebSite.productsgroups', verbose_name='گروه بنر 2'),
        ),
        migrations.AlterField(
            model_name='firstpagebaners',
            name='group3',
            field=models.ForeignKey(blank=True, default='0', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group3', to='WebSite.productsgroups', verbose_name='گروه بنر 3'),
        ),
        migrations.AlterField(
            model_name='firstpagebaners',
            name='group4',
            field=models.ForeignKey(blank=True, default='0', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group4', to='WebSite.productsgroups', verbose_name='گروه بنر 4'),
        ),
        migrations.AlterField(
            model_name='firstpagebaners',
            name='group5',
            field=models.ForeignKey(blank=True, default='0', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group5', to='WebSite.productsgroups', verbose_name='گروه بنر 5'),
        ),
        migrations.AlterField(
            model_name='firstpagebaners',
            name='group6',
            field=models.ForeignKey(blank=True, default='0', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group6', to='WebSite.productsgroups', verbose_name='گروه بنر 6'),
        ),
        migrations.AlterField(
            model_name='firstpagebaners',
            name='group7',
            field=models.ForeignKey(blank=True, default='0', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group7', to='WebSite.productsgroups', verbose_name='گروه بنر 7'),
        ),
        migrations.AlterField(
            model_name='firstpagebaners',
            name='group8',
            field=models.ForeignKey(blank=True, default='0', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group8', to='WebSite.productsgroups', verbose_name='گروه بنر 8'),
        ),
        migrations.AlterField(
            model_name='firstpagebaners',
            name='group9',
            field=models.ForeignKey(blank=True, default='0', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group9', to='WebSite.productsgroups', verbose_name='گروه بنر 9'),
        ),
        migrations.AlterField(
            model_name='sellbascket',
            name='pdiscount',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='تخیف کالا'),
        ),
        migrations.AlterField(
            model_name='sellbascket',
            name='pprise',
            field=models.BigIntegerField(default=0, verbose_name='قیمت کالا'),
        ),
        migrations.AlterField(
            model_name='spfactor',
            name='date1',
            field=django_jalali.db.models.jDateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='تاریخ اول'),
        ),
        migrations.AlterField(
            model_name='spfactor',
            name='date2',
            field=django_jalali.db.models.jDateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='تاریخ دوم'),
        ),
    ]
