# Generated by Django 3.0.9 on 2021-09-16 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0004_auto_20210827_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='brand',
            field=models.ForeignKey(blank=True, default=0, max_length=200, null=True, on_delete=django.db.models.deletion.PROTECT, to='WebSite.productsbrands', verbose_name='نام برند'),
        ),
        migrations.AlterField(
            model_name='products',
            name='serial',
            field=models.CharField(blank=True, default=0, max_length=200, null=True, verbose_name='شماره سریال'),
        ),
    ]
