# Generated by Django 3.0.9 on 2021-10-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0005_auto_20210916_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='priceorg',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='قیمت محصول'),
        ),
    ]
