# Generated by Django 3.0.9 on 2021-10-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0006_products_priceorg'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='specialcell',
            field=models.BooleanField(blank=True, default=0, null=True, verbose_name='فروش ویژه'),
        ),
    ]
