# Generated by Django 3.0.9 on 2021-10-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0008_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='sociallink',
            field=models.CharField(blank=True, default='****', max_length=200, null=True, verbose_name='لینک شبکه اجتماعی'),
        ),
    ]
