# Generated by Django 3.0.9 on 2021-11-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0009_products_sociallink'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalcheckout',
            name='BankTrackingCode',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='کد رهگیری بانک '),
        ),
        migrations.AddField(
            model_name='finalcheckout',
            name='bank_card_no',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره کارت بانکی مشتری'),
        ),
    ]
