# Generated by Django 3.2.8 on 2021-11-03 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0010_auto_20211101_1827'),
    ]

    operations = [
       
        migrations.AlterModelTable(
            name='main',
            table='Main1',
        ),
    ]
