# Generated by Django 3.0.9 on 2022-05-08 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0013_auto_20220507_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsparamerts',
            name='bid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='WebSite.productsbrands', verbose_name='برند'),
        ),
        migrations.AddField(
            model_name='productsparamerts',
            name='changetobrand',
            field=models.CharField(blank=True, choices=[('0', '--------'), ('1', 'فعال'), ('2', 'غیر فعال')], default='False', max_length=200, null=True, verbose_name='وضعیت برند'),
        ),
    ]
