# Generated by Django 3.2.8 on 2021-11-03 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('WebSite', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='discountfinal',
            name='DiscountToCustomers',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='تخفیف بر روی مشتری'),
        ),
        migrations.AddField(
            model_name='discountfinal',
            name='DiscountToGoods',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.PROTECT, to='WebSite.productsgroups', verbose_name='تخفیف بر روی گروه کالا'),
        ),
        migrations.AddField(
            model_name='cost',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WebSite.products', verbose_name='نام محصول'),
        ),
        migrations.AddField(
            model_name='commentdetails',
            name='cid',
            field=models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.PROTECT, to='WebSite.comment', verbose_name='کد کامنت'),
        ),
        migrations.AddField(
            model_name='comment',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WebSite.products', verbose_name='کد محصول'),
        ),
    ]
