# Generated by Django 3.0.9 on 2022-05-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0003_auto_20220423_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalcheckout',
            name='sendtype',
            field=models.IntegerField(blank=True, choices=[(0, 'تحویل حضوری'), (1, 'ارسال با پیک'), (2, 'ارسال با پست پیش تاز'), (3, 'رزرو سفارش')], default=0, null=True, verbose_name='روش ارسال'),
        ),
        migrations.AlterField(
            model_name='sellbascket',
            name='status',
            field=models.IntegerField(choices=[(0, 'سفارش'), (1, 'پرداخت شده'), (2, 'کنسل شده'), (3, 'رزرو شده')], default=0, verbose_name='وضعیت خرید'),
        ),
        migrations.AlterField(
            model_name='usersendtype',
            name='sendtype',
            field=models.IntegerField(blank=True, choices=[(0, 'تحویل حضوری'), (1, 'ارسال با پیک'), (2, 'ارسال با پست پیش تاز'), (3, 'رزرو سفارش')], default=0, null=True, verbose_name='روش ارسال'),
        ),
    ]
