# Generated by Django 3.0.9 on 2022-05-04 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0004_auto_20220501_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='productscolors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default=0, max_length=200, verbose_name='رمگ')),
                ('hezacode', models.CharField(default=0, max_length=200, verbose_name='کد رنگ')),
                ('Create_Date', models.DateTimeField(auto_now=True)),
                ('Update_Date', models.DateTimeField(auto_now_add=True)),
                ('Create_Uid', models.IntegerField(blank=True, default=0, null=True, verbose_name='کاربر ایجاد کننده')),
                ('Update_Uid', models.IntegerField(blank=True, default=0, null=True, verbose_name='کاربر ویرایش کننده')),
            ],
            options={
                'verbose_name': 'رنگ ',
                'verbose_name_plural': 'رنگ ها',
                'db_table': 'productscolors',
                'ordering': ['id'],
                'permissions': (('can_read_private_section', 'administrator'), ('SubAdmin', 'SubAdmin'), ('user_watcher', 'User')),
            },
        ),
        migrations.CreateModel(
            name='productssize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seize', models.CharField(default=0, max_length=200, verbose_name='رمگ')),
                ('Create_Date', models.DateTimeField(auto_now=True)),
                ('Update_Date', models.DateTimeField(auto_now_add=True)),
                ('Create_Uid', models.IntegerField(blank=True, default=0, null=True, verbose_name='کاربر ایجاد کننده')),
                ('Update_Uid', models.IntegerField(blank=True, default=0, null=True, verbose_name='کاربر ویرایش کننده')),
            ],
            options={
                'verbose_name': 'سایز ',
                'verbose_name_plural': 'سایز ها',
                'db_table': 'productssize',
                'ordering': ['id'],
                'permissions': (('can_read_private_section', 'administrator'), ('SubAdmin', 'SubAdmin'), ('user_watcher', 'User')),
            },
        ),
        migrations.CreateModel(
            name='productsparamerts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productinventory', models.CharField(default=0, max_length=200, verbose_name='کد رنگ')),
                ('productprice', models.CharField(default=0, max_length=200, verbose_name='کد رنگ')),
                ('Create_Date', models.DateTimeField(auto_now=True)),
                ('Update_Date', models.DateTimeField(auto_now_add=True)),
                ('Create_Uid', models.IntegerField(blank=True, default=0, null=True, verbose_name='کاربر ایجاد کننده')),
                ('Update_Uid', models.IntegerField(blank=True, default=0, null=True, verbose_name='کاربر ویرایش کننده')),
                ('cid', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='colorname', to='WebSite.productscolors', verbose_name='رنگ')),
                ('pid', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='productsname', to='WebSite.products', verbose_name='نام کالا')),
                ('sid', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='sizename', to='WebSite.productssize', verbose_name='سایز')),
            ],
            options={
                'verbose_name': 'کالا ',
                'verbose_name_plural': 'کالا ها',
                'db_table': 'productsparamerts',
                'ordering': ['id'],
                'permissions': (('can_read_private_section', 'administrator'), ('SubAdmin', 'SubAdmin'), ('user_watcher', 'User')),
            },
        ),
    ]
