# Generated by Django 3.0.9 on 2022-05-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0006_auto_20220504_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productssize',
            old_name='seize',
            new_name='size',
        ),
        migrations.AlterField(
            model_name='productscolors',
            name='color',
            field=models.CharField(default=0, max_length=200, verbose_name='رنگ'),
        ),
    ]
