# Generated by Django 3.0.9 on 2022-05-04 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0007_auto_20220504_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsparamerts',
            name='productinventory',
            field=models.CharField(default=0, max_length=200, verbose_name='تعداد'),
        ),
        migrations.AlterField(
            model_name='productsparamerts',
            name='productprice',
            field=models.CharField(default=0, max_length=200, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='productssize',
            name='size',
            field=models.CharField(default=0, max_length=200, verbose_name='سایز'),
        ),
    ]
