# Generated by Django 3.0.9 on 2022-05-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0008_auto_20220505_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsparamerts',
            name='changetocolor',
            field=models.BooleanField(blank=True, default=0, null=True, verbose_name='وضعیت رنگ'),
        ),
        migrations.AddField(
            model_name='productsparamerts',
            name='changetosize',
            field=models.BooleanField(blank=True, default=0, null=True, verbose_name='وضعیت سایز'),
        ),
    ]
