# Generated by Django 3.0.9 on 2022-05-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0009_auto_20220506_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsparamerts',
            name='changetocolor',
            field=models.BooleanField(blank=True, default='False', null=True, verbose_name='وضعیت رنگ'),
        ),
        migrations.AlterField(
            model_name='productsparamerts',
            name='changetosize',
            field=models.BooleanField(blank=True, default='False', null=True, verbose_name='وضعیت سایز'),
        ),
    ]
