# Generated by Django 3.0.9 on 2022-05-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0010_auto_20220506_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsparamerts',
            name='changetocolor',
            field=models.CharField(blank=True, choices=[('1', 'فعال'), ('2', 'غیر فعال')], default='False', max_length=200, null=True, verbose_name='وضعیت رنگ'),
        ),
        migrations.AlterField(
            model_name='productsparamerts',
            name='changetosize',
            field=models.CharField(blank=True, choices=[('1', 'فعال'), ('2', 'غیر فعال')], default='False', max_length=200, null=True, verbose_name='وضعیت سایز'),
        ),
    ]
