# Generated by Django 3.0.9 on 2022-05-07 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0012_auto_20220506_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsparamerts',
            name='cid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='WebSite.productscolors', verbose_name='رنگ'),
        ),
        migrations.AlterField(
            model_name='productsparamerts',
            name='pid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='WebSite.products', verbose_name='نام کالا'),
        ),
        migrations.AlterField(
            model_name='productsparamerts',
            name='sid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='WebSite.productssize', verbose_name='سایز'),
        ),
    ]
