# Generated by Django 3.0.9 on 2022-05-08 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0014_auto_20220508_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsparamerts',
            name='bid',
        ),
        migrations.RemoveField(
            model_name='productsparamerts',
            name='changetobrand',
        ),
    ]
