# Generated by Django 3.0.9 on 2022-05-09 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0016_auto_20220508_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsparamerts',
            name='bid',
        ),
        migrations.RemoveField(
            model_name='productsparamerts',
            name='changetobrand',
        ),
    ]
