# Generated by Django 3.0.9 on 2022-05-19 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0017_auto_20220509_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellbascket',
            name='colorid_bycolor',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='کد رنگ بر اساس رنگ'),
        ),
        migrations.AddField(
            model_name='sellbascket',
            name='colorid_bysize',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='کد رنگ بر اساس سایز'),
        ),
        migrations.AddField(
            model_name='sellbascket',
            name='sizeid_bycolor',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='کد سایز بر اساس رنگ'),
        ),
        migrations.AddField(
            model_name='sellbascket',
            name='sizeid_bysize',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='کد سایز بر اساس سایز'),
        ),
    ]
