# Generated by Django 3.0.9 on 2022-05-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0018_auto_20220519_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellbascket',
            name='orginalprice',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='قیمت اصلی کالا'),
        ),
    ]
