# Generated by Django 3.0.9 on 2022-05-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0019_sellbascket_orginalprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsparamerts',
            name='takhfif',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='تخفیف'),
        ),
    ]
