# Generated by Django 3.0.9 on 2022-05-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0020_productsparamerts_takhfif'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsparamerts',
            name='takhfifprice',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='ملغ تخفیف'),
        ),
        migrations.AlterField(
            model_name='productsparamerts',
            name='takhfif',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='مبلغ پس از تخفیف'),
        ),
    ]
