# Generated by Django 3.0.9 on 2022-05-26 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0021_auto_20220525_1642'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Main',
        ),
    ]
