# Generated by Django 3.0.9 on 2022-05-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0022_delete_main'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.TextField()),
                ('payment_id', models.TextField()),
                ('amount', models.IntegerField()),
                ('date', models.TextField(default='-')),
                ('card_number', models.TextField(default='****')),
                ('idpay_track_id', models.IntegerField(default=0)),
                ('bank_track_id', models.TextField(default=0)),
                ('status', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'سفارش ',
                'verbose_name_plural': 'سفارش ها',
                'db_table': 'Main',
                'ordering': ['id'],
                'permissions': (('can_read_private_section', 'administrator'), ('SubAdmin', 'SubAdmin'), ('user_watcher', 'User')),
            },
        ),
    ]
