# Generated by Django 3.0.9 on 2022-05-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0024_sellbascket_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalcheckout',
            name='colorid_bycolor',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='کد رنگ بر اساس رنگ'),
        ),
        migrations.AddField(
            model_name='finalcheckout',
            name='colorid_bysize',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='کد رنگ بر اساس سایز'),
        ),
        migrations.AddField(
            model_name='finalcheckout',
            name='order_id',
            field=models.CharField(blank=True, default='0', max_length=128, null=True, verbose_name='ای دی سفارش'),
        ),
        migrations.AddField(
            model_name='finalcheckout',
            name='orginalprice',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='قیمت اصلی کالا'),
        ),
        migrations.AddField(
            model_name='finalcheckout',
            name='sizeid_bycolor',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='کد سایز بر اساس رنگ'),
        ),
        migrations.AddField(
            model_name='finalcheckout',
            name='sizeid_bysize',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='کد سایز بر اساس سایز'),
        ),
    ]
