# Generated by Django 3.0.9 on 2022-05-26 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0025_auto_20220526_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalcheckout',
            name='orginalprice',
        ),
    ]
