# Generated by Django 3.0.9 on 2022-05-27 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0026_remove_finalcheckout_orginalprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsparamerts',
            name='productinventory_remain',
            field=models.BigIntegerField(default=0, max_length=200, verbose_name='تعداد باقی مانده'),
        ),
        migrations.AddField(
            model_name='productsparamerts',
            name='productinventory_sold',
            field=models.BigIntegerField(default=0, max_length=200, verbose_name='تعداد فروخته شده'),
        ),
    ]
