# Generated by Django 3.0.9 on 2022-05-27 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0027_auto_20220527_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsparamerts',
            name='productinventory_remain',
            field=models.BigIntegerField(default=0, verbose_name='تعداد باقی مانده'),
        ),
        migrations.AlterField(
            model_name='productsparamerts',
            name='productinventory_sold',
            field=models.BigIntegerField(default=0, verbose_name='تعداد فروخته شده'),
        ),
    ]
