# Generated by Django 3.0.9 on 2022-05-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0028_auto_20220527_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsparamerts',
            name='changetocolor',
        ),
        migrations.RemoveField(
            model_name='productsparamerts',
            name='changetosize',
        ),
        migrations.AlterField(
            model_name='productsparamerts',
            name='productinventory',
            field=models.CharField(default=0, max_length=200, verbose_name='تعداد اولیه'),
        ),
    ]
