# Generated by Django 3.0.9 on 2022-05-31 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0029_auto_20220527_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsparamerts',
            name='pdesc',
            field=models.TextField(blank=True, default='', max_length=500, null=True, verbose_name='توضیح'),
        ),
    ]
