# Generated by Django 3.0.9 on 2022-06-02 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0030_productsparamerts_pdesc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='idpay_track_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
