# Generated by Django 3.0.9 on 2022-06-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0031_auto_20220603_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsparamerts',
            name='productinventory_recharge',
            field=models.CharField(default=0, max_length=200, verbose_name='تعداد شارژ شده'),
        ),
    ]
