# Generated by Django 3.0.9 on 2022-06-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0033_auto_20220614_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsparamerts',
            name='productinventory_recharge',
            field=models.BigIntegerField(default=0, verbose_name='تعداد شارژ شده'),
        ),
    ]
