# Generated by Django 3.0.9 on 2022-06-14 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0034_auto_20220614_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='productsoaraminvcharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productinventory', models.BigIntegerField(default=0, max_length=200, verbose_name='تعداد اولیه')),
                ('productinventory_recharge', models.BigIntegerField(default=0, verbose_name='تعداد شارژ شده')),
                ('productinventory_sold', models.BigIntegerField(default=0, verbose_name='تعداد فروخته شده')),
                ('productinventory_remain', models.BigIntegerField(default=0, verbose_name='تعداد باقی مانده')),
                ('pdesc', models.TextField(blank=True, default='', max_length=500, null=True, verbose_name='توضیح')),
                ('Create_Date', models.DateTimeField(auto_now=True)),
                ('Update_Date', models.DateTimeField(auto_now_add=True)),
                ('Create_Uid', models.IntegerField(blank=True, default=0, null=True, verbose_name='کاربر ایجاد کننده')),
                ('Update_Uid', models.IntegerField(blank=True, default=0, null=True, verbose_name='کاربر ویرایش کننده')),
                ('cid', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='WebSite.productscolors', verbose_name='رنگ')),
                ('pid', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='WebSite.products', verbose_name='نام کالا')),
                ('sid', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='WebSite.productssize', verbose_name='سایز')),
            ],
            options={
                'verbose_name': 'کالا ',
                'verbose_name_plural': 'کالا ها',
                'db_table': 'productsoaraminvcharge',
                'ordering': ['id'],
                'permissions': (('can_read_private_section', 'administrator'), ('SubAdmin', 'SubAdmin'), ('user_watcher', 'User')),
            },
        ),
    ]
