# Generated by Django 3.0.9 on 2022-06-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0035_productsoaraminvcharge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsoaraminvcharge',
            name='productinventory',
            field=models.BigIntegerField(default=0, verbose_name='تعداد اولیه'),
        ),
    ]
