# Generated by Django 3.0.9 on 2022-06-14 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0036_auto_20220614_1917'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='productsoaraminvcharge',
            new_name='productsparaminvcharge',
        ),
        migrations.AlterModelTable(
            name='productsparaminvcharge',
            table='productsparaminvcharge',
        ),
    ]
