# Generated by Django 3.0.9 on 2022-06-15 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0038_auto_20220614_2201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsparaminvcharge',
            old_name='cid',
            new_name='invcid',
        ),
        migrations.RenameField(
            model_name='productsparaminvcharge',
            old_name='pid',
            new_name='invpid',
        ),
        migrations.RenameField(
            model_name='productsparaminvcharge',
            old_name='sid',
            new_name='invsid',
        ),
    ]
