# Generated by Django 3.0.9 on 2022-06-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0042_auto_20220624_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost',
            name='pricetype',
            field=models.IntegerField(blank=True, null=True, verbose_name=' روش تخفیف '),
        ),
    ]
