# Generated by Django 3.0.9 on 2022-06-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0045_auto_20220624_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='colorid',
            field=models.CharField(blank=True, default=0, max_length=256, null=True, verbose_name='کد رنگ'),
        ),
        migrations.AlterField(
            model_name='cost',
            name='gid',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name=' کد گروه کالا'),
        ),
        migrations.AlterField(
            model_name='cost',
            name='pid',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name=' کد کالا '),
        ),
        migrations.AlterField(
            model_name='cost',
            name='sizeid',
            field=models.CharField(blank=True, default=0, max_length=256, null=True, verbose_name='کد سایز'),
        ),
    ]
