# Generated by Django 3.0.9 on 2022-07-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0047_auto_20220701_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellbascket',
            name='FactorNo',
        ),
        migrations.AddField(
            model_name='finalcheckout',
            name='colorid_bycolor',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='کد رنگ بر اساس رنگ'),
        ),
        migrations.AddField(
            model_name='finalcheckout',
            name='colorid_bysize',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='کد رنگ بر اساس سایز'),
        ),
        migrations.AddField(
            model_name='finalcheckout',
            name='sizeid_bycolor',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='کد سایز بر اساس رنگ'),
        ),
        migrations.AddField(
            model_name='finalcheckout',
            name='sizeid_bysize',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='کد سایز بر اساس سایز'),
        ),
        migrations.AlterField(
            model_name='finalcheckout',
            name='postcode',
            field=models.CharField(blank=True, default=0, max_length=128, null=True, verbose_name='کد مرسوله'),
        ),
    ]
