# Generated by Django 3.0.9 on 2022-07-01 14:04

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0048_auto_20220701_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='mastertakhfif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField(blank=True, default=0, null=True, verbose_name='نام محصول')),
                ('gid', models.IntegerField(blank=True, default=0, null=True, verbose_name='گروه محصول')),
                ('price', models.BigIntegerField(blank=True, null=True, verbose_name='مبلغ تخفیف')),
                ('priceoffpercent', models.IntegerField(blank=True, default=0, null=True, verbose_name=' درصد تخفیف')),
                ('colorid', models.IntegerField(blank=True, default=0, null=True, verbose_name='رنگ محصول')),
                ('sizeid', models.IntegerField(blank=True, default=0, null=True, verbose_name='سایز محصول')),
                ('takhfiftype', models.BigIntegerField(blank=True, null=True, verbose_name='نوع تخفیف')),
                ('takhfifpricetype', models.BigIntegerField(blank=True, null=True, verbose_name='نوع مبلغ')),
                ('desc', models.TextField(blank=True, max_length=4000, null=True, verbose_name='توضیحات')),
                ('Create_Date', models.DateTimeField(auto_now=True)),
                ('Update_Date', models.DateTimeField(auto_now_add=True)),
                ('Create_Uid', models.IntegerField(blank=True, default=0, null=True, verbose_name='کاربر ایجاد کننده')),
                ('Update_Uid', models.IntegerField(blank=True, default=0, null=True, verbose_name='کاربر ویرایش کننده')),
            ],
            options={
                'verbose_name': ' تخفیف',
                'verbose_name_plural': 'تخفیف ها',
                'db_table': 'mastertakhfif',
                'ordering': ['id'],
                'permissions': (('can_read_private_section', 'administrator'), ('SubAdmin', 'SubAdmin'), ('user_watcher', 'User')),
            },
        ),
        migrations.AlterModelOptions(
            name='cost',
            options={'ordering': ['id'], 'permissions': (('can_read_private_section', 'administrator'), ('SubAdmin', 'SubAdmin'), ('user_watcher', 'User')), 'verbose_name': 'قیمت', 'verbose_name_plural': 'قیمت ها'},
        ),
        migrations.RemoveField(
            model_name='cost',
            name='colorid',
        ),
        migrations.RemoveField(
            model_name='cost',
            name='gid',
        ),
        migrations.RemoveField(
            model_name='cost',
            name='price',
        ),
        migrations.RemoveField(
            model_name='cost',
            name='priceoffpercent',
        ),
        migrations.RemoveField(
            model_name='cost',
            name='sizeid',
        ),
        migrations.RemoveField(
            model_name='cost',
            name='takhfifpricetype',
        ),
        migrations.RemoveField(
            model_name='cost',
            name='takhfiftype',
        ),
        migrations.AddField(
            model_name='cost',
            name='effdate',
            field=django_jalali.db.models.jDateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='تاریخ موثر'),
        ),
        migrations.AddField(
            model_name='cost',
            name='priceoff',
            field=models.BigIntegerField(default='0', verbose_name='قیمت محصول پس از تخفیف'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cost',
            name='priceorg',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='قیمت محصول'),
        ),
        migrations.AddField(
            model_name='cost',
            name='specialcell',
            field=models.BooleanField(blank=True, default=0, null=True, verbose_name='فروش ویژه'),
        ),
        migrations.AlterField(
            model_name='cost',
            name='pid',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.PROTECT, to='WebSite.products', verbose_name='نام محصول'),
            preserve_default=False,
        ),
    ]
