# Generated by Django 3.0.9 on 2022-07-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0049_auto_20220701_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastertakhfif',
            name='colorid',
            field=models.CharField(blank=True, default=0, max_length=256, null=True, verbose_name='رنگ محصول'),
        ),
        migrations.AlterField(
            model_name='mastertakhfif',
            name='gid',
            field=models.CharField(blank=True, default=0, max_length=256, null=True, verbose_name='گروه محصول'),
        ),
        migrations.AlterField(
            model_name='mastertakhfif',
            name='pid',
            field=models.CharField(blank=True, default=0, max_length=256, null=True, verbose_name='نام محصول'),
        ),
        migrations.AlterField(
            model_name='mastertakhfif',
            name='sizeid',
            field=models.CharField(blank=True, default=0, max_length=256, null=True, verbose_name='سایز محصول'),
        ),
    ]
