# Generated by Django 3.0.9 on 2022-07-03 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0050_auto_20220701_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastertakhfif',
            name='colorid_name',
            field=models.CharField(blank=True, default=0, max_length=256, null=True, verbose_name='رنگ محصول'),
        ),
        migrations.AddField(
            model_name='mastertakhfif',
            name='gid_name',
            field=models.CharField(blank=True, default=0, max_length=256, null=True, verbose_name='گروه محصول'),
        ),
        migrations.AddField(
            model_name='mastertakhfif',
            name='pid_name',
            field=models.CharField(blank=True, default=0, max_length=256, null=True, verbose_name='نام محصول'),
        ),
        migrations.AddField(
            model_name='mastertakhfif',
            name='sizeid_name',
            field=models.CharField(blank=True, default=0, max_length=256, null=True, verbose_name='سایز محصول'),
        ),
        migrations.AlterField(
            model_name='mastertakhfif',
            name='colorid',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='کد محصول'),
        ),
        migrations.AlterField(
            model_name='mastertakhfif',
            name='gid',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='کد محصول'),
        ),
        migrations.AlterField(
            model_name='mastertakhfif',
            name='pid',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='کد محصول'),
        ),
        migrations.AlterField(
            model_name='mastertakhfif',
            name='sizeid',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='کد محصول'),
        ),
    ]
