# Generated by Django 3.0.9 on 2022-07-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0051_auto_20220703_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsgroups',
            name='GroupOrders',
            field=models.IntegerField(choices=[(0, 'اولویت یک'), (1, 'اولویت دو'), (2, 'اولویت سه'), (4, 'اولویت چهار'), (5, 'اولویت پنج'), (6, 'اولویت شش'), (7, 'اولویت هفت'), (8, 'اولویت هشت'), (9, 'اولویت نه'), (10, 'اولویت ده')], default=0, verbose_name='اولویت نمایش'),
        ),
    ]
