# Generated by Django 3.0.9 on 2022-07-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0052_productsgroups_grouporders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discountfinal',
            name='DCustomers',
        ),
        migrations.RemoveField(
            model_name='discountfinal',
            name='DProducts',
        ),
        migrations.RemoveField(
            model_name='discountfinal',
            name='DiscountCode',
        ),
        migrations.RemoveField(
            model_name='discountfinal',
            name='DiscountName',
        ),
        migrations.RemoveField(
            model_name='discountfinal',
            name='DiscountPriceToSend',
        ),
        migrations.RemoveField(
            model_name='discountfinal',
            name='DiscountToCustomers',
        ),
        migrations.RemoveField(
            model_name='discountfinal',
            name='DiscountToGoods',
        ),
        migrations.RemoveField(
            model_name='discountfinal',
            name='DiscounttotalPriceToSend',
        ),
        migrations.RemoveField(
            model_name='discountfinal',
            name='LimitEndDate',
        ),
        migrations.RemoveField(
            model_name='discountfinal',
            name='LimitStartDate',
        ),
        migrations.RemoveField(
            model_name='discountfinal',
            name='ShowToCustomers',
        ),
        migrations.RemoveField(
            model_name='discountfinal',
            name='changetoproductsgroup',
        ),
        migrations.RemoveField(
            model_name='discountfinal',
            name='chengepricetoPercent',
        ),
        migrations.RemoveField(
            model_name='discountfinal',
            name='chengetocustomersgroup',
        ),
        migrations.RemoveField(
            model_name='discountfinal',
            name='chengetocustosendprice',
        ),
        migrations.RemoveField(
            model_name='discountfinal',
            name='dpricePercent',
        ),
        migrations.AddField(
            model_name='discountfinal',
            name='DmaxCountToSend',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='سقف تعداد برای ارسال'),
        ),
        migrations.AddField(
            model_name='discountfinal',
            name='ErsalPrice',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='مبلغ هزینه ارسال'),
        ),
        migrations.AlterField(
            model_name='discountfinal',
            name='DmaxPriceToSend',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='سقف مبلغ برای ارسال'),
        ),
        migrations.AlterField(
            model_name='productsgroups',
            name='GroupOrders',
            field=models.IntegerField(choices=[(-1, 'بدون اولویت'), (0, 'اولویت یک'), (1, 'اولویت دو'), (2, 'اولویت سه'), (4, 'اولویت چهار'), (5, 'اولویت پنج'), (6, 'اولویت شش'), (7, 'اولویت هفت'), (8, 'اولویت هشت'), (9, 'اولویت نه'), (10, 'اولویت ده')], default=0, verbose_name='اولویت نمایش'),
        ),
        migrations.DeleteModel(
            name='DiscountCreate',
        ),
    ]
