# Generated by Django 3.0.9 on 2022-07-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0053_auto_20220710_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountfinal',
            name='Dmax_Type',
            field=models.IntegerField(choices=[(0, 'بدون روش'), (1, 'براساس مبلغ'), (2, 'براساس مقدار'), (3, 'براساس مبلغ و مقدار')], default=0, verbose_name='نوع عملیات'),
        ),
    ]
