# Generated by Django 3.0.9 on 2022-07-27 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0054_discountfinal_dmax_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsparamerts',
            name='paramserial',
            field=models.CharField(default=0, max_length=200, verbose_name='سریال کالا'),
        ),
    ]
