# Generated by Django 3.0.9 on 2022-08-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0056_auto_20220823_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinPidAndCid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductID', models.CharField(default=0, max_length=200)),
                ('CategoryID', models.CharField(default=0, max_length=200)),
                ('Create_Date', models.DateTimeField(auto_now=True)),
                ('Update_Date', models.DateTimeField(auto_now_add=True)),
                ('Create_Uid', models.IntegerField(blank=True, default=0, null=True, verbose_name='کاربر ایجاد کننده')),
                ('Update_Uid', models.IntegerField(blank=True, default=0, null=True, verbose_name='کاربر ویرایش کننده')),
            ],
            options={
                'db_table': 'JoinPidAndCid',
                'ordering': ['id'],
                'permissions': (('can_read_private_section', 'administrator'),),
            },
        ),
    ]
