# Generated by Django 3.0.9 on 2022-08-26 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0059_auto_20220826_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banners',
            name='group1',
            field=models.ForeignKey(blank=True, default='0', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group1', to='WebSite.ProductsGroups'),
        ),
        migrations.AlterField(
            model_name='banners',
            name='group10',
            field=models.ForeignKey(blank=True, default='0', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group10', to='WebSite.ProductsGroups'),
        ),
        migrations.AlterField(
            model_name='banners',
            name='group11',
            field=models.ForeignKey(blank=True, default='0', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group11', to='WebSite.ProductsGroups'),
        ),
        migrations.AlterField(
            model_name='banners',
            name='group2',
            field=models.ForeignKey(blank=True, default='0', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group2', to='WebSite.ProductsGroups'),
        ),
        migrations.AlterField(
            model_name='banners',
            name='group3',
            field=models.ForeignKey(blank=True, default='0', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group3', to='WebSite.ProductsGroups'),
        ),
        migrations.AlterField(
            model_name='banners',
            name='group4',
            field=models.ForeignKey(blank=True, default='0', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group4', to='WebSite.ProductsGroups'),
        ),
        migrations.AlterField(
            model_name='banners',
            name='group5',
            field=models.ForeignKey(blank=True, default='0', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group5', to='WebSite.ProductsGroups'),
        ),
        migrations.AlterField(
            model_name='banners',
            name='group6',
            field=models.ForeignKey(blank=True, default='0', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group6', to='WebSite.ProductsGroups'),
        ),
        migrations.AlterField(
            model_name='banners',
            name='group7',
            field=models.ForeignKey(blank=True, default='0', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group7', to='WebSite.ProductsGroups'),
        ),
        migrations.AlterField(
            model_name='banners',
            name='group8',
            field=models.ForeignKey(blank=True, default='0', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group8', to='WebSite.ProductsGroups'),
        ),
        migrations.AlterField(
            model_name='banners',
            name='group9',
            field=models.ForeignKey(blank=True, default='0', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group9', to='WebSite.ProductsGroups'),
        ),
        migrations.AlterField(
            model_name='buybasket',
            name='pid',
            field=models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.PROTECT, to='WebSite.Products', verbose_name='کد محصول'),
        ),
        migrations.AlterField(
            model_name='masterusers',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CGroup', to='WebSite.CustomersGroup'),
        ),
        migrations.AlterField(
            model_name='products',
            name='group',
            field=models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.PROTECT, to='WebSite.ProductsGroups', verbose_name='نام گروه'),
        ),
        migrations.AlterField(
            model_name='productscomments',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WebSite.Products'),
        ),
        migrations.AlterField(
            model_name='productsparametrs',
            name='pid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='WebSite.Products', verbose_name='نام کالا'),
        ),
        migrations.AlterField(
            model_name='productstars',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WebSite.Products'),
        ),
    ]
