# Generated by Django 3.0.9 on 2022-09-10 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0063_auto_20220909_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banners',
            name='group1',
            field=models.ForeignKey(blank=True, default='0', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group1', to='WebSite.ProductsGroups'),
        ),
        migrations.AlterField(
            model_name='banners',
            name='group10',
            field=models.ForeignKey(blank=True, default='0', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group10', to='WebSite.ProductsGroups'),
        ),
        migrations.AlterField(
            model_name='banners',
            name='group11',
            field=models.ForeignKey(blank=True, default='0', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group11', to='WebSite.ProductsGroups'),
        ),
        migrations.AlterField(
            model_name='banners',
            name='group2',
            field=models.ForeignKey(blank=True, default='0', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group2', to='WebSite.ProductsGroups'),
        ),
        migrations.AlterField(
            model_name='banners',
            name='group3',
            field=models.ForeignKey(blank=True, default='0', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group3', to='WebSite.ProductsGroups'),
        ),
        migrations.AlterField(
            model_name='banners',
            name='group4',
            field=models.ForeignKey(blank=True, default='0', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group4', to='WebSite.ProductsGroups'),
        ),
        migrations.AlterField(
            model_name='banners',
            name='group5',
            field=models.ForeignKey(blank=True, default='0', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group5', to='WebSite.ProductsGroups'),
        ),
        migrations.AlterField(
            model_name='banners',
            name='group6',
            field=models.ForeignKey(blank=True, default='0', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group6', to='WebSite.ProductsGroups'),
        ),
        migrations.AlterField(
            model_name='banners',
            name='group7',
            field=models.ForeignKey(blank=True, default='0', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group7', to='WebSite.ProductsGroups'),
        ),
        migrations.AlterField(
            model_name='banners',
            name='group8',
            field=models.ForeignKey(blank=True, default='0', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group8', to='WebSite.ProductsGroups'),
        ),
        migrations.AlterField(
            model_name='banners',
            name='group9',
            field=models.ForeignKey(blank=True, default='0', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group9', to='WebSite.ProductsGroups'),
        ),
        migrations.AlterField(
            model_name='buybasket',
            name='pid',
            field=models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.PROTECT, to='WebSite.Products', verbose_name='کد محصول'),
        ),
        migrations.AlterField(
            model_name='masterusers',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CGroup', to='WebSite.CustomersGroup'),
        ),
        migrations.AlterField(
            model_name='products',
            name='group',
            field=models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.PROTECT, to='WebSite.ProductsGroups', verbose_name='نام گروه'),
        ),
        migrations.AlterField(
            model_name='productscomments',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WebSite.Products'),
        ),
        migrations.AlterField(
            model_name='productsgroups',
            name='GroupOrders',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=0, verbose_name='اولویت نمایش'),
        ),
        migrations.AlterField(
            model_name='productsparametrs',
            name='pid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='WebSite.Products', verbose_name='نام کالا'),
        ),
        migrations.AlterField(
            model_name='productstars',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WebSite.Products'),
        ),
    ]
